In [1]:
import numpy as np

In [2]:
array = np.array([[1,2,3],
                 [4,5,6],
                 [7,8,9]])
print('array type:', type(array))
print('array 형태:', array.shape)

array type: <class 'numpy.ndarray'>
array 형태: (3, 3)


In [3]:
array.ndim

2

In [4]:
#astype()을 통해 데이터 타입 변경(메모리 절약, float -> int로 바꾸자)
array_float = np.array([1.,2.,3.])
print(array_float.dtype)
array_int = array_float.astype('int32')
print(array_int.dtype)

float64
int32


In [5]:
a = np.arange(10)
print('array1:\n',a)
b = np.zeros((3,2))
print('array2:\n',b)
c = np.ones((3,2))
print('array3:\n',c)

a_reshape = a.reshape(2,5)
print('array1_reshape:\n',a_reshape)

array1:
 [0 1 2 3 4 5 6 7 8 9]
array2:
 [[0. 0.]
 [0. 0.]
 [0. 0.]]
array3:
 [[1. 1.]
 [1. 1.]
 [1. 1.]]
array1_reshape:
 [[0 1 2 3 4]
 [5 6 7 8 9]]


In [6]:
#단일값 추출
array1 = np.arange(1,10)
print(array1)
print('0번째 값:',array1[0]) #0번째 값 추출
print('뒤에서 2번째 값:', array1[-2])
array1[-2] = -8 #값 수정
print(array1)
print('--------------2차원 array-------------')
array2 = np.arange(1,10).reshape(3,3)
print(array2)
print('0행 0열:', array2[0,0])
print('1행 2열:', array2[1,2])

[1 2 3 4 5 6 7 8 9]
0번째 값: 1
뒤에서 2번째 값: 8
[ 1  2  3  4  5  6  7 -8  9]
--------------2차원 array-------------
[[1 2 3]
 [4 5 6]
 [7 8 9]]
0행 0열: 1
1행 2열: 6


In [7]:
#슬라이싱
array1 = np.arange(1,10)
print(array1[:])
print(array1[0:3])
print(array1[3:])
print('--------------2차원 array-------------')
array2 = np.arange(1,10).reshape(3,3)
print(array2[:])
print('2번째 열만',array2[:,2])
print(array2[1:,1:])

[1 2 3 4 5 6 7 8 9]
[1 2 3]
[4 5 6 7 8 9]
--------------2차원 array-------------
[[1 2 3]
 [4 5 6]
 [7 8 9]]
2번째 열만 [3 6 9]
[[5 6]
 [8 9]]


In [8]:
#불린 인덱싱 (조건 필터링과 검색을 동시에 할 수 있음)
array1 = np.arange(1,10)
array1[array1>5]

array([6, 7, 8, 9])

In [9]:
#sort
array1 = [3,1,9,5]
print(np.sort(array1)) #원본은 변경x
print(array1)
print('-----------------------------------------')
print(array1.sort()) #원본 변경O
print(array1)
print('내림차순 정렬:', np.sort(array1)[::-1])
print('--------------2차원 array-------------')
array2 = np.array([[8,12],
                  [7,1]])
print('행 방향으로 정렬\n', np.sort(array2, axis=0))
print('열 방향으로 정렬\n', np.sort(array2, axis=1))

[1 3 5 9]
[3, 1, 9, 5]
-----------------------------------------
None
[1, 3, 5, 9]
내림차순 정렬: [9 5 3 1]
--------------2차원 array-------------
행 방향으로 정렬
 [[ 7  1]
 [ 8 12]]
열 방향으로 정렬
 [[ 8 12]
 [ 1  7]]


In [10]:
#argsort
array1 = [3,1,5,0]
print(np.argsort(array1)) #[0,1,3,5]
print(np.argsort(array1)[::-1]) #[5,3,1,0]

[3 1 0 2]
[2 0 1 3]


In [11]:
a = np.arange(1,7).reshape(2,3)
b = np.arange(7,13).reshape(3,2)
c = np.arange(1,5).reshape(2,2)
print('두 행렬의 내적\n',np.dot(a,b))
print('전치행렬\n',np.transpose(c))

두 행렬의 내적
 [[ 58  64]
 [139 154]]
전치행렬
 [[1 3]
 [2 4]]


In [12]:
import pandas as pd

In [13]:
titanic_df = pd.read_csv('titanic.csv')
titanic_df.head(3)

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S

In [14]:
titanic_df.shape

(891, 12)

In [15]:
titanic_df['Pclass'].value_counts()

3    491
1    216
2    184
Name: Pclass, dtype: int64

In [16]:
col_name = ['col1', 'col2', 'col3']
array = np.array([[1,2,3],
                 [4,5,6]])
#ndarray를 dataframe으로
df_array = pd.DataFrame(array, columns=col_name)
print(df_array)

   col1  col2  col3
0     1     2     3
1     4     5     6


In [17]:
dict_ = {'col1':[1,11], 'col2':[2,22]}
df_dict = pd.DataFrame(dict_)
print(df_dict)

   col1  col2
0     1     2
1    11    22


In [18]:
#dataframe을 ndarray로
array_df = df_dict.values
print(type(array_df))
#dataframe을 리스트로
list_df = df_dict.values.tolist()
print(type(list_df))
#dataframe을 딕셔너리로
dict_df = df_dict.to_dict('list')
print(type(dict_df))

<class 'numpy.ndarray'>
<class 'list'>
<class 'dict'>


In [19]:
#칼럼 데이터 세트 생성
titanic_df['Age_0'] = 0
#기존 칼럼을 이용해 새로운 칼럼 생성
titanic_df['Family_No'] = titanic_df['SibSp'] + titanic_df['Parch'] + 1
#칼럼 데이터 세트 수정
titanic_df['Age_0'] = titanic_df['Age_0'] + 100
titanic_df.head(3)

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   

   Parch            Ticket     Fare Cabin Embarked  Age_0  Family_No  
0      0         A/5 21171   7.2500   NaN        S    100          2  
1      0          PC 17599  71.2833   C85        C    100          2  
2      0  STON/O2. 3101282   7.9250   NaN        S    100          1

In [20]:
titanic_drop_df = titanic_df.drop(['Age_0', 'Family_No'], axis=1)
titanic_drop_df.head(3)

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S

In [21]:
titanic_df = pd.read_csv('titanic.csv')

In [22]:
titanic_df[0]

KeyError: 0

In [23]:
titanic_df[titanic_df['Age']>60]

PassengerId  Survived  Pclass                                       Name  \
33            34         0       2                      Wheadon, Mr. Edward H   
54            55         0       1             Ostby, Mr. Engelhart Cornelius   
96            97         0       1                  Goldschmidt, Mr. George B   
116          117         0       3                       Connors, Mr. Patrick   
170          171         0       1                  Van der hoef, Mr. Wyckoff   
252          253         0       1                  Stead, Mr. William Thomas   
275          276         1       1          Andrews, Miss. Kornelia Theodosia   
280          281         0       3                           Duane, Mr. Frank   
326          327         0       3                  Nysveen, Mr. Johan Hansen   
438          439         0       1                          Fortune, Mr. Mark   
456          457         0       1                  Millet, Mr. Francis Davis   
483          484         1       3                     Turkula, Mrs. (Hedwig)   
493          494         0       1                    Artagaveytia, Mr. Ramon   
545          546         0       1               Nicholson, Mr. Arthur Ernest   
555          556         0       1                         Wright, Mr. George   
570          571         1       2                         Harris, Mr. George   
625          626         0       1                      Sutton, Mr. Frederick   
630          631         1       1       Barkworth, Mr. Algernon Henry Wilson   
672          673         0       2                Mitchell, Mr. Henry Michael   
745          746         0       1               Crosby, Capt. Edward Gifford   
829          830         1       1  Stone, Mrs. George Nelson (Martha Evelyn)   
851          852         0       3                        Svensson, Mr. Johan   

        Sex   Age  SibSp  Parch       Ticket      Fare        Cabin Embarked  
33     male  66.0      0      0   C.A. 24579   10.5000          NaN        S  
54     male  65.0      0      1       113509   61.9792          B30        C  
96     male  71.0      0      0     PC 17754   34.6542           A5        C  
116    male  70.5      0      0       370369    7.7500          NaN        Q  
170    male  61.0      0      0       111240   33.5000          B19        S  
252    male  62.0      0      0       113514   26.5500          C87        S  
275  female  63.0      1      0        13502   77.9583           D7        S  
280    male  65.0      0      0       336439    7.7500          NaN        Q  
326    male  61.0      0      0       345364    6.2375          NaN        S  
438    male  64.0      1      4        19950  263.0000  C23 C25 C27        S  
456    male  65.0      0      0        13509   26.5500          E38        S  
483  female  63.0      0      0         4134    9.5875          NaN        S  
493    male  71.0      0      0     PC 17609   49.5042          NaN        C  
545    male  64.0      0      0          693   26.0000          NaN        S  
555    male  62.0      0      0       113807   26.5500          NaN        S  
570    male  62.0      0      0  S.W./PP 752   10.5000          NaN        S  
625    male  61.0      0      0        36963   32.3208          D50        S  
630    male  80.0      0      0        27042   30.0000          A23        S  
672    male  70.0      0      0   C.A. 24580   10.5000          NaN        S  
745    male  70.0      1      1    WE/P 5735   71.0000          B22        S  
829  female  62.0      0      0       113572   80.0000          B28      NaN  
851    male  74.0      0      0       347060    7.7750          NaN        S

In [24]:
titanic_df[titanic_df['Age']>60][['Name', 'Age']].head(3)

Name   Age
33           Wheadon, Mr. Edward H  66.0
54  Ostby, Mr. Engelhart Cornelius  65.0
96       Goldschmidt, Mr. George B  71.0

In [25]:
titanic_df.loc[titanic_df['Age']>60, ['Name', 'Age']].head(3)

Name   Age
33           Wheadon, Mr. Edward H  66.0
54  Ostby, Mr. Engelhart Cornelius  65.0
96       Goldschmidt, Mr. George B  71.0

In [26]:
titanic_sorted = titanic_df.sort_values(by=['Pclass', 'Name'], ascending=False)
titanic_sorted.head(3)

PassengerId  Survived  Pclass                             Name   Sex  \
868          869         0       3      van Melkebeke, Mr. Philemon  male   
153          154         0       3  van Billiard, Mr. Austin Blyler  male   
282          283         0       3        de Pelsmaeker, Mr. Alfons  male   

      Age  SibSp  Parch    Ticket  Fare Cabin Embarked  
868   NaN      0      0    345777   9.5   NaN        S  
153  40.5      0      2  A/5. 851  14.5   NaN        S  
282  16.0      0      0    345778   9.5   NaN        S

In [27]:
#모든 칼럼의 해당 aggregation 적용
titanic_df.count()
#지정한 칼럼만 aggregation 적용
titanic_df[['Age','Fare']].mean()

Age     29.699118
Fare    32.204208
dtype: float64

In [28]:
titanic_df.groupby('Pclass')[['PassengerId','Survived']].count()

PassengerId  Survived
Pclass                       
1               216       216
2               184       184
3               491       491

In [29]:
agg_format = {'Age':'max', 'SibSp':'sum', 'Fare':'mean'}
titanic_df.groupby('Pclass').agg(agg_format)

Age  SibSp       Fare
Pclass                        
1       80.0     90  84.154687
2       70.0     74  20.662183
3       74.0    302  13.675550

In [30]:
#결손데이터 처리
titanic_df.isna().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [31]:
titanic_df['Cabin'] = titanic_df['Cabin'].fillna('C000')
titanic_df['Age'] = titanic_df['Age'].fillna(titanic_df['Age'].mean())
titanic_df['Embarked'] = titanic_df['Embarked'].fillna('S')
titanic_df.isna().sum()

PassengerId    0
Survived       0
Pclass         0
Name           0
Sex            0
Age            0
SibSp          0
Parch          0
Ticket         0
Fare           0
Cabin          0
Embarked       0
dtype: int64

---------------------------------------------

In [33]:
import sklearn
print(sklearn.__version__)

0.23.1


In [40]:
import sklearn
from sklearn.datasets import load_iris
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split
import pandas as pd

#붓꽃 데이터셋 로딩
iris = load_iris()
iris_data = iris.data
iris_label = iris.target

#붓꽃 데이터셋을 DataFrame으로 변환
iris_df = pd.DataFrame(data=iris_data, columns=iris.feature_names)
iris_df['label'] = iris.target
iris_df.head(3)

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   

   label  
0      0  
1      0  
2      0

In [43]:
#학습데이터(80%), 테스트 데이터(20%) 분리
X_train, X_test, y_train, y_test = train_test_split(iris_data, iris_label, test_size=0.2, random_state=11)
#DecisionTreeClassifier 객체 생성
dt_clf = DecisionTreeClassifier(random_state=11)
#학습 수행
dt_clf.fit(X_train, y_train) #학습 데이터 기반으로 학습 완료
#학습이 완료된 DecisionTreeClassifier 객체에서 테스트 데이터 세트로 예측 수행
pred = dt_clf.predict(X_test)

from sklearn.metrics import accuracy_score
print('예측 정확도:', accuracy_score(y_test,pred))

예측 정확도: 0.9333333333333333


In [46]:
#학습데이터(70%), 테스트 데이터(30%)분리
dt_clf = DecisionTreeClassifier(random_state=121)
iris_data=load_iris()

X_train, X_test, y_train, y_test = train_test_split(iris_data.data, iris_data.target, test_size=0.3, random_state=121)
dt_clf.fit(X_train, y_train)
pred = dt_clf.predict(X_test)
accuracy_score(y_test, pred)

0.9555555555555556

In [47]:
#K-FOLD 교차 검증
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score
from sklearn.model_selection import KFold
import numpy as np

iris = load_iris()
features = iris.data
label = iris.target
dt_clf = DecisionTreeClassifier(random_state=123)

#5개의 폴드 세트로 분리하는 KFold 객체와 폴드 세트별 정확도를 담을 리스트 객체 생성
kfold = KFold(n_splits=5)
cv_accuracy = []
#전체 붓꽃 데이터는 모두 150개, 따라서 학습용 데이터 세트는 이 중 4/5인 120개, 검증용 데이터 세트는 30개로 분할

n_iter = 0
#KFold 객체의 split()을 호출하면 폴드 별 학습용, 검증용 테스트의 row index를 array로 반환
for train_index, test_index in kfold.split(features):
    #kfold.split으로 반환된 인덱스를 이용해 학습용, 검증용 테스트 데이터 추출
    X_train, X_test = features[train_index], features[test_index]
    y_train, y_test = label[train_index], label[test_index]
    #학습 및 예측
    dt_clf.fit(X_train, y_train)
    pred = dt_clf.predict(X_test)
    n_iter += 1
    #반복할때마다 정확도 측정
    accuracy = np.round(accuracy_score(y_test, pred), 4)
    train_size = X_train.shape[0]
    test_size = X_test.shape[0]
    print(n_iter, '교차 검증 정확도:',accuracy, '학습 데이터 크기',train_size, '검증 데이터 크기', test_size)
    print(n_iter, '검증 세트 인덱스:',test_index)
    cv_accuracy.append(accuracy)
    
#개별 iteration별 정확도를 합하여 평균 정확도 계산
print('평균 검증 정확도:', np.mean(cv_accuracy))


1 교차 검증 정확도: 1.0 학습 데이터 크기 120 검증 데이터 크기 30
1 검증 세트 인덱스: [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]
2 교차 검증 정확도: 0.9667 학습 데이터 크기 120 검증 데이터 크기 30
2 검증 세트 인덱스: [30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53
 54 55 56 57 58 59]
3 교차 검증 정확도: 0.9 학습 데이터 크기 120 검증 데이터 크기 30
3 검증 세트 인덱스: [60 61 62 63 64 65 66 67 68 69 70 71 72 73 74 75 76 77 78 79 80 81 82 83
 84 85 86 87 88 89]
4 교차 검증 정확도: 0.9333 학습 데이터 크기 120 검증 데이터 크기 30
4 검증 세트 인덱스: [ 90  91  92  93  94  95  96  97  98  99 100 101 102 103 104 105 106 107
 108 109 110 111 112 113 114 115 116 117 118 119]
5 교차 검증 정확도: 0.8 학습 데이터 크기 120 검증 데이터 크기 30
5 검증 세트 인덱스: [120 121 122 123 124 125 126 127 128 129 130 131 132 133 134 135 136 137
 138 139 140 141 142 143 144 145 146 147 148 149]
평균 검증 정확도: 0.9199999999999999


In [48]:
#Stratified KFold
from sklearn.model_selection import StratifiedKFold

skf = StratifiedKFold(n_splits=3)
n_iter = 0

for train_index, test_index in skf.split(iris_df, iris_df['label']):
    n_iter += 1
    label_train = iris_df['label'].iloc[train_index]
    label_test = iris_df['label'].iloc[test_index]
    print('교차검증:',n_iter)
    print('학습 레이블 데이터 분포: \n', label_train.value_counts())
    print('검증 레이블 데이터 분포: \n', label_test.value_counts())

교차검증: 1
학습 레이블 데이터 분포: 
 2    34
1    33
0    33
Name: label, dtype: int64
검증 레이블 데이터 분포: 
 1    17
0    17
2    16
Name: label, dtype: int64
교차검증: 2
학습 레이블 데이터 분포: 
 1    34
2    33
0    33
Name: label, dtype: int64
검증 레이블 데이터 분포: 
 2    17
0    17
1    16
Name: label, dtype: int64
교차검증: 3
학습 레이블 데이터 분포: 
 0    34
2    33
1    33
Name: label, dtype: int64
검증 레이블 데이터 분포: 
 2    17
1    17
0    16
Name: label, dtype: int64


In [51]:
dt_clf = DecisionTreeClassifier(random_state=156)

skfold = StratifiedKFold(n_splits=3)
cv_accuracy = []
n_iter = 0

for train_index, test_index in skfold.split(features, label):
    #split으로 반환된 인덱스를 이용해 학습용, 검증용 테스트 데이터 추출
    X_train, X_test = features[train_index], features[test_index]
    y_train, y_test = label[train_index], label[test_index]
    #학습 및 예측
    dt_clf.fit(X_train, y_train)
    pred = dt_clf.predict(X_test)
    n_iter += 1
    #반복할때마다 정확도 측정
    accuracy = np.round(accuracy_score(y_test, pred), 4)
    train_size = X_train.shape[0]
    test_size = X_test.shape[0]
    print(n_iter, '교차 검증 정확도:',accuracy, '학습 데이터 크기',train_size, '검증 데이터 크기', test_size)
    print(n_iter, '검증 세트 인덱스:',test_index)
    cv_accuracy.append(accuracy)
    
#개별 iteration별 정확도를 합하여 평균 정확도 계산
print('평균 검증 정확도:', np.mean(cv_accuracy))

1 교차 검증 정확도: 0.98 학습 데이터 크기 100 검증 데이터 크기 50
1 검증 세트 인덱스: [  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  50
  51  52  53  54  55  56  57  58  59  60  61  62  63  64  65  66 100 101
 102 103 104 105 106 107 108 109 110 111 112 113 114 115]
2 교차 검증 정확도: 0.94 학습 데이터 크기 100 검증 데이터 크기 50
2 검증 세트 인덱스: [ 17  18  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  67
  68  69  70  71  72  73  74  75  76  77  78  79  80  81  82 116 117 118
 119 120 121 122 123 124 125 126 127 128 129 130 131 132]
3 교차 검증 정확도: 0.98 학습 데이터 크기 100 검증 데이터 크기 50
3 검증 세트 인덱스: [ 34  35  36  37  38  39  40  41  42  43  44  45  46  47  48  49  83  84
  85  86  87  88  89  90  91  92  93  94  95  96  97  98  99 133 134 135
 136 137 138 139 140 141 142 143 144 145 146 147 148 149]
평균 검증 정확도: 0.9666666666666667


In [52]:
#cross_val_score() 사용하기
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import cross_val_score, cross_validate
from sklearn.datasets import load_iris

iris_data = load_iris()
dt_clf = DecisionTreeClassifier(random_state=123)

data = iris_data.data
label = iris_data.target

#성능 지표는 accuracy, 교차 검증 세트는 3개
scores = cross_val_score(dt_clf, data, label, scoring='accuracy', cv=3)
print('교차 검증별 정확도:', np.round(scores,4))
print('평균 검증 정확도:', np.round(np.mean(scores),4))

교차 검증별 정확도: [0.98 0.94 0.98]
평균 검증 정확도: 0.9667


In [54]:
from sklearn.datasets import load_iris
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import GridSearchCV
import pandas as pd

#데이터를 로딩하고 학습 데이터와 테스트 데이터 분리
iris_data = load_iris()
X_train,X_test,y_train,y_test = train_test_split(iris_data.data, iris_data.target, test_size=0.2, random_state=123)
dtree = DecisionTreeClassifier()

#파라미터를 딕셔너리 형태로 설정
parameters = {'max_depth':[1,2,3], 'min_samples_split':[2,3]}
#param_grid의 하이퍼 파라미터를 3개의 train, test set fold로 나누어 테스트 수행 설정
#refit=True가 디폴트 값. 가장 좋은 파라미터 설정으로 재학습 시킴.
grid_dtree = GridSearchCV(dtree, param_grid=parameters, cv=3, refit=True)

#붓꽃 학습 데이터로 param_grid의 하이퍼 파라미터를 순차적으로 학습, 평가
grid_dtree.fit(X_train, y_train)

#GridSearchCV 결과를 추출해 DataFrame으로 변환
scores_df = pd.DataFrame(grid_dtree.cv_results_)
scores_df[['params', 'mean_test_score', 'rank_test_score', 'split0_test_score', 'split1_test_score', 'split2_test_score']]

params  mean_test_score  rank_test_score  \
0  {'max_depth': 1, 'min_samples_split': 2}            0.675                5   
1  {'max_depth': 1, 'min_samples_split': 3}            0.675                5   
2  {'max_depth': 2, 'min_samples_split': 2}            0.925                1   
3  {'max_depth': 2, 'min_samples_split': 3}            0.925                1   
4  {'max_depth': 3, 'min_samples_split': 2}            0.925                1   
5  {'max_depth': 3, 'min_samples_split': 3}            0.925                1   

   split0_test_score  split1_test_score  split2_test_score  
0              0.675              0.675              0.675  
1              0.675              0.675              0.675  
2              0.975              0.900              0.900  
3              0.975              0.900              0.900  
4              0.975              0.900              0.900  
5              0.975              0.900              0.900

In [55]:
print('GridSearchCV 최적 파라미터:', grid_dtree.best_params_)
print('GridSearchCV 최고 정확도:', grid_dtree.best_score_)

GridSearchCV 최적 파라미터: {'max_depth': 2, 'min_samples_split': 2}
GridSearchCV 최고 정확도: 0.9249999999999999


In [57]:
#레이블 인코딩
from sklearn.preprocessing import LabelEncoder

items = ['TV', '냉장고', '전자레인지', '컴퓨터', '선풍기', '선풍기']

#LabelEncoder를 객체로 생성한 후 fit()과 transform()으로 레이블 인코딩 수행
encoder = LabelEncoder()
encoder.fit(items)
labels = encoder.transform(items)
print('인코딩 변환값:', labels)
print('인코딩 클래스:', encoder.classes_)

인코딩 변환값: [0 1 3 4 2 2]
인코딩 클래스: ['TV' '냉장고' '선풍기' '전자레인지' '컴퓨터']


In [58]:
from sklearn.preprocessing import OneHotEncoder
import numpy as np

items = ['TV', '냉장고', '전자레인지', '컴퓨터', '선풍기', '선풍기']
#먼저 숫자 값으로 변환을 위헤 LabelEncoder로 변환
encoder = LabelEncoder()
encoder.fit(items)
labels = encoder.transform(items)
#2차원 데이터로 변환
labels = labels.reshape(-1,1)

#OneHot Encoding
oh_encoder = OneHotEncoder()
oh_encoder.fit(labels)
oh_labels = oh_encoder.transform(labels)
print('One-Hot 인코딩 데이터')
print(oh_labels.toarray())
print('One-Hot 인코딩 데이터 차원')
print(oh_labels.shape)

One-Hot 인코딩 데이터
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]
 [0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0.]]
One-Hot 인코딩 데이터 차원
(6, 5)


In [59]:
import pandas as pd

df = pd.DataFrame({'item':['TV', '냉장고', '전자레인지', '컴퓨터', '선풍기', '선풍기']})
pd.get_dummies(df)

item_TV  item_냉장고  item_선풍기  item_전자레인지  item_컴퓨터
0        1         0         0           0         0
1        0         1         0           0         0
2        0         0         0           1         0
3        0         0         0           0         1
4        0         0         1           0         0
5        0         0         1           0         0

In [60]:
#StandardScaler
from sklearn.datasets import load_iris
from sklearn.preprocessing import StandardScaler
import pandas as pd

#데이터 세트 로드 후 데이터 프레임으로 변환
iris = load_iris()
iris_data = iris.data
iris_df = pd.DataFrame(data=iris_data, columns=iris.feature_names)

#StandardScaler 객체 생성
scaler = StandardScaler()
#StandardScaler로 데이터 세트 변환, fit()과 transform() 호출
scaler.fit(iris_df)
iris_scaled = scaler.transform(iris_df)

#transform() 했을 때 스케일 변환된 데이터 세트가 ndarray로 변환되어 이를 DataFrame으로 변환
iris_df_scaled = pd.DataFrame(data=iris_scaled, columns=iris.feature_names)
print('feature들의 평균값:')
print(iris_df_scaled.mean())
print('feature들의 분산값:')
print(iris_df_scaled.var())

feature들의 평균값:
sepal length (cm)   -1.690315e-15
sepal width (cm)    -1.842970e-15
petal length (cm)   -1.698641e-15
petal width (cm)    -1.409243e-15
dtype: float64
feature들의 분산값:
sepal length (cm)    1.006711
sepal width (cm)     1.006711
petal length (cm)    1.006711
petal width (cm)     1.006711
dtype: float64


In [62]:
#MinMaxScaler
from sklearn.preprocessing import MinMaxScaler

#MinMaxScaler 객체 생성
scaler = MinMaxScaler()
#MinMaxScaler로 데이터 세트 변환
scaler.fit(iris_df)
iris_scaled = scaler.transform(iris_df)

iris_df_scaled = pd.DataFrame(data=iris_scaled, columns=iris.feature_names)
print('feature들의 최솟값:')
print(iris_df_scaled.min())
print('feature들의 최댓값:')
print(iris_df_scaled.max())

feature들의 최솟값:
sepal length (cm)    0.0
sepal width (cm)     0.0
petal length (cm)    0.0
petal width (cm)     0.0
dtype: float64
feature들의 최댓값:
sepal length (cm)    1.0
sepal width (cm)     1.0
petal length (cm)    1.0
petal width (cm)     1.0
dtype: float64


In [63]:
from sklearn.metrics import accuracy_score, precision_score, recall_score, confusion_matrix

def get_clf_eval(y_test, pred):
    confusion = confusion_matrix(y_test, pred)
    accuracy = accuracy_score(y_test, pred)
    precision = precision_score(y_test,pred)
    recall = recall_score(y_test,pred)
    print('오차행렬')
    print(confusion)
    print('정확도:',accuracy, '정밀도:',precision, '재현율:',precision)

In [ ]:
#로지스틱 회귀 기반 타이타닉 생존자 예측
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression

titanic_df = pd.read_csv('titanic.csv')
y_titanic_df = titanic_df['Survived']
X_titanic_df = titanic_df.drop('Survived', axis=1)
X_titanic_df = transform_features(X_titanic_df)